import { AITool } from './types';

export const AI_TOOLS: AITool[] = [
  {
    id: '1',
    name: 'Luminary AI',
    shortDescription: 'Generative image creation with hyper-realistic capabilities.',
    fullDescription: 'Luminary AI is a cutting-edge image generation platform that allows creators to turn text prompts into stunning, high-resolution visuals. Featuring advanced controls for lighting, composition, and style, it is designed for professionals and hobbyists alike.',
    category: 'Image',
    pricing: 'Freemium',
    rating: 4.8,
    reviewCount: 1240,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=1',
    tags: ['Generative Art', 'Design', 'Creative'],
    launchDate: '2023-11-15',
    featured: true,
  },
  {
    id: '2',
    name: 'Codex Pro',
    shortDescription: 'Intelligent code completion and refactoring assistant.',
    fullDescription: 'Codex Pro integrates directly into your IDE to provide real-time code suggestions, bug detection, and automated refactoring. It supports over 20 languages and learns from your unique coding style to become more helpful over time.',
    category: 'Code',
    pricing: 'Paid',
    rating: 4.9,
    reviewCount: 850,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=2',
    tags: ['Developer Tools', 'Productivity', 'Automation'],
    launchDate: '2023-08-01',
    featured: true,
  },
  {
    id: '3',
    name: 'VoiceSynthetix',
    shortDescription: 'Realistic text-to-speech with emotional intelligence.',
    fullDescription: 'Create lifelike voiceovers for videos, podcasts, and presentations. VoiceSynthetix offers a library of over 500 voices in 60 languages, with granular control over pitch, speed, and emotional tone.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.6,
    reviewCount: 320,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=3',
    tags: ['TTS', 'Audio Editing', 'Content Creation'],
    launchDate: '2024-01-20',
  },
  {
    id: '4',
    name: 'WriteFlow',
    shortDescription: 'AI-powered copywriting assistant for marketing teams.',
    fullDescription: 'WriteFlow helps marketing teams generate high-converting copy for ads, emails, and landing pages. It includes built-in SEO optimization and collaboration features to streamline the content creation workflow.',
    category: 'Text',
    pricing: 'Free',
    rating: 4.5,
    reviewCount: 2100,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=4',
    tags: ['Marketing', 'Copywriting', 'SEO'],
    launchDate: '2022-05-10',
  },
  {
    id: '5',
    name: 'VidGenius',
    shortDescription: 'Turn blog posts into engaging short-form videos.',
    fullDescription: 'VidGenius analyzes written content and automatically generates video scripts, selects stock footage, and adds voiceovers. Perfect for repurposing content for TikTok, Reels, and YouTube Shorts.',
    category: 'Video',
    pricing: 'Paid',
    rating: 4.2,
    reviewCount: 150,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=5',
    tags: ['Video Editing', 'Social Media', 'Automation'],
    launchDate: '2023-12-05',
  },
  {
    id: '6',
    name: 'DataSense',
    shortDescription: 'Automated data analysis and visualization tool.',
    fullDescription: 'Upload any CSV or connect a database, and DataSense will automatically detect patterns, create charts, and generate actionable insights in plain English.',
    category: 'Productivity',
    pricing: 'Enterprise',
    rating: 4.7,
    reviewCount: 400,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=6',
    tags: ['Analytics', 'Business Intelligence', 'Data'],
    launchDate: '2023-09-15',
  },
  {
    id: '7',
    name: 'ModelMaker 3D',
    shortDescription: 'Generate 3D assets from text descriptions.',
    fullDescription: 'Rapidly prototype game assets and architectural elements. ModelMaker 3D outputs industry-standard .obj and .fbx files compatible with Unity, Unreal Engine, and Blender.',
    category: '3D',
    pricing: 'Freemium',
    rating: 4.3,
    reviewCount: 220,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=7',
    tags: ['Game Dev', 'Modeling', 'Prototyping'],
    launchDate: '2024-02-10',
  },
  {
    id: '8',
    name: 'ChatOptimize',
    shortDescription: 'Customer support automation with human-like empathy.',
    fullDescription: 'A chatbot solution that goes beyond basic FAQs. ChatOptimize understands context, sentiment, and intent to resolve complex customer issues without human intervention.',
    category: 'Text',
    pricing: 'Paid',
    rating: 4.4,
    reviewCount: 600,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=8',
    tags: ['Support', 'Chatbot', 'Business'],
    launchDate: '2023-03-22',
  },
  {
    id: '9',
    name: 'MusicMinds',
    shortDescription: 'AI composer for royalty-free background music.',
    fullDescription: 'Generate infinite streams of unique music tailored to specific moods, genres, and lengths. Perfect for content creators needing safe-to-use background tracks.',
    category: 'Audio',
    pricing: 'Free',
    rating: 4.1,
    reviewCount: 180,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=9',
    tags: ['Music', 'Streaming', 'Creative'],
    launchDate: '2023-07-08',
  },
  {
    id: '10',
    name: 'BugBuster',
    shortDescription: 'Automated testing and QA for web applications.',
    fullDescription: 'BugBuster autonomously navigates your web app, identifying UI glitches, broken links, and performance bottlenecks before your users do.',
    category: 'Code',
    pricing: 'Enterprise',
    rating: 4.8,
    reviewCount: 95,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=10',
    tags: ['QA', 'Testing', 'DevOps'],
    launchDate: '2024-01-05',
  },
  {
    id: '11',
    name: 'PresentAI',
    shortDescription: 'Create professional slide decks in seconds.',
    fullDescription: 'Input a topic or upload a document, and PresentAI builds a complete slide deck with layout, images, and speaker notes.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.5,
    reviewCount: 1200,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=11',
    tags: ['Presentation', 'Business', 'Design'],
    launchDate: '2022-11-30',
  },
  {
    id: '12',
    name: 'TranscribeNow',
    shortDescription: 'Real-time meeting transcription and summarization.',
    fullDescription: 'Never take meeting notes again. TranscribeNow records, transcribes, and summarizes your Zoom, Teams, and Google Meet calls, extracting key action items automatically.',
    category: 'Productivity',
    pricing: 'Paid',
    rating: 4.7,
    reviewCount: 3000,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=12',
    tags: ['Meetings', 'Notes', 'Efficiency'],
    launchDate: '2023-04-12',
  },
  {
    id: '13',
    name: 'LogoFast',
    shortDescription: 'Instant logo generation with AI suggestions.',
    fullDescription: 'Generate beautiful, minimalist logos in seconds. Tweak colors, fonts, and icons with AI guidance to match your brand identity perfectly.',
    category: 'Image',
    pricing: 'Free',
    rating: 4.6,
    reviewCount: 450,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=13',
    tags: ['Design', 'Branding', 'Startup'],
    launchDate: '2023-01-10',
  },
  {
    id: '14',
    name: 'LegalEase',
    shortDescription: 'AI contract analysis and simplification.',
    fullDescription: 'Upload complex legal documents and get simple, plain-English summaries. Identify risky clauses and missing terms automatically.',
    category: 'Text',
    pricing: 'Paid',
    rating: 4.3,
    reviewCount: 180,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=14',
    tags: ['Legal', 'Business', 'Analysis'],
    launchDate: '2023-06-15',
  },
  {
    id: '15',
    name: 'HealthBot 24/7',
    shortDescription: 'Preliminary medical symptom checker and advice.',
    fullDescription: 'A sophisticated medical AI that helps users understand their symptoms and decide whether to see a doctor. Trained on vetted medical literature.',
    category: 'Text',
    pricing: 'Free',
    rating: 4.1,
    reviewCount: 890,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=15',
    tags: ['Health', 'Wellness', 'Advice'],
    launchDate: '2022-09-01',
  },
  {
    id: '16',
    name: 'CodeWhisperer',
    shortDescription: 'Secure code companion for enterprise developers.',
    fullDescription: 'Focuses on security compliance and best practices while suggesting code. Scans for vulnerabilities in real-time as you type.',
    category: 'Code',
    pricing: 'Enterprise',
    rating: 4.7,
    reviewCount: 560,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=16',
    tags: ['Security', 'DevOps', 'Coding'],
    launchDate: '2023-10-05',
  },
  {
    id: '17',
    name: 'SoundScaper',
    shortDescription: 'Generate ambient noise and soundscapes for focus.',
    fullDescription: 'Create custom sound environments for work, sleep, or meditation. Mix rain, cafe noise, and synth drones generated on the fly.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.8,
    reviewCount: 330,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=17',
    tags: ['Wellness', 'Productivity', 'Audio'],
    launchDate: '2023-02-14',
  },
  {
    id: '18',
    name: 'RenderReal',
    shortDescription: 'Photorealistic architectural rendering from sketches.',
    fullDescription: 'Upload a rough sketch of a building or room, and RenderReal turns it into a photorealistic visualization with accurate lighting and textures.',
    category: 'Image',
    pricing: 'Paid',
    rating: 4.5,
    reviewCount: 210,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=18',
    tags: ['Architecture', 'Design', 'Rendering'],
    launchDate: '2023-11-20',
  },
  {
    id: '19',
    name: 'VideoTranslate',
    shortDescription: 'Dub videos into other languages with lip-sync.',
    fullDescription: 'Automatically translate your video content into 30+ languages. The AI adjusts the speaker\'s lip movements to match the new language.',
    category: 'Video',
    pricing: 'Paid',
    rating: 4.9,
    reviewCount: 1100,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=19',
    tags: ['Localization', 'Video', 'Translation'],
    launchDate: '2024-01-08',
  },
  {
    id: '20',
    name: 'ResumeRocket',
    shortDescription: 'Tailor your resume to specific job descriptions.',
    fullDescription: 'Paste your resume and a job description. ResumeRocket rewrites your bullet points to highlight relevant skills and pass ATS filters.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.4,
    reviewCount: 2500,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=20',
    tags: ['Career', 'Writing', 'Jobs'],
    launchDate: '2022-08-15',
  },
  {
    id: '21',
    name: 'GameNPC',
    shortDescription: 'Dynamic dialogue generation for game characters.',
    fullDescription: 'Give your NPCs a personality and backstory, and GameNPC generates infinite, context-aware dialogue options for players.',
    category: 'Code',
    pricing: 'Freemium',
    rating: 4.6,
    reviewCount: 400,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=21',
    tags: ['Game Dev', 'Narrative', 'Writing'],
    launchDate: '2023-05-30',
  },
  {
    id: '22',
    name: 'StockMind',
    shortDescription: 'Predictive analytics for retail stock trading.',
    fullDescription: 'Analyze market sentiment from news and social media to predict short-term stock movements. (Not financial advice).',
    category: 'Productivity',
    pricing: 'Paid',
    rating: 4.0,
    reviewCount: 600,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=22',
    tags: ['Finance', 'Trading', 'Analytics'],
    launchDate: '2023-03-10',
  },
  {
    id: '23',
    name: 'PhotoFixer',
    shortDescription: 'Restore and colorize old black-and-white photos.',
    fullDescription: 'Bring family history to life. Remove scratches, sharpen faces, and add realistic color to vintage photographs instantly.',
    category: 'Image',
    pricing: 'Free',
    rating: 4.7,
    reviewCount: 900,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=23',
    tags: ['Photography', 'Restoration', 'History'],
    launchDate: '2022-12-01',
  },
  {
    id: '24',
    name: 'EmailGuard',
    shortDescription: 'Detect phishing and malicious emails in real-time.',
    fullDescription: 'An AI layer for your inbox that analyzes sender behavior and link safety to flag sophisticated phishing attempts.',
    category: 'Productivity',
    pricing: 'Enterprise',
    rating: 4.8,
    reviewCount: 150,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=24',
    tags: ['Security', 'Email', 'Business'],
    launchDate: '2023-09-25',
  },
  {
    id: '25',
    name: 'InteriorAI',
    shortDescription: 'Virtual interior design and staging.',
    fullDescription: 'Take a photo of an empty room and see it fully furnished in various styles (Modern, Scandinavian, Industrial, etc.).',
    category: 'Image',
    pricing: 'Paid',
    rating: 4.4,
    reviewCount: 550,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=25',
    tags: ['Real Estate', 'Design', 'Home'],
    launchDate: '2023-04-05',
  },
  {
    id: '26',
    name: 'VoiceCloner',
    shortDescription: 'Clone your own voice for content creation.',
    fullDescription: 'Train an AI model on 5 minutes of your speech to generate endless voiceovers that sound exactly like you.',
    category: 'Audio',
    pricing: 'Paid',
    rating: 4.6,
    reviewCount: 220,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=26',
    tags: ['Cloning', 'Voice', 'Personalization'],
    launchDate: '2023-11-01',
  },
  {
    id: '27',
    name: 'MathSolver Plus',
    shortDescription: 'Step-by-step solution for complex calculus problems.',
    fullDescription: 'Scan a handwritten math problem and get a detailed breakdown of the solution logic, not just the final answer.',
    category: 'Productivity',
    pricing: 'Free',
    rating: 4.9,
    reviewCount: 3000,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=27',
    tags: ['Education', 'Math', 'Students'],
    launchDate: '2022-09-15',
  },
  {
    id: '28',
    name: 'BeatMaker',
    shortDescription: 'Generate drum beats and rhythms for producers.',
    fullDescription: 'Stuck on a beat? Generate unique drum patterns in any genre (Trap, House, Lo-Fi) and export as MIDI.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.3,
    reviewCount: 180,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=28',
    tags: ['Music Production', 'Drums', 'Creative'],
    launchDate: '2023-06-20',
  },
  {
    id: '29',
    name: 'CopyCheck',
    shortDescription: 'Plagiarism detection and AI writing probability.',
    fullDescription: 'Check if content was written by a human or AI. Useful for educators and publishers to ensure originality.',
    category: 'Text',
    pricing: 'Paid',
    rating: 4.2,
    reviewCount: 400,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=29',
    tags: ['Education', 'Writing', 'Compliance'],
    launchDate: '2023-02-01',
  },
  {
    id: '30',
    name: 'AvatarGen',
    shortDescription: 'Create 3D avatars from a single selfie.',
    fullDescription: 'Generate a rigged 3D avatar that looks like you, ready for use in VR chat, games, or the metaverse.',
    category: '3D',
    pricing: 'Freemium',
    rating: 4.5,
    reviewCount: 670,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=30',
    tags: ['Metaverse', 'Social', 'Gaming'],
    launchDate: '2023-08-20',
  },
  {
    id: '31',
    name: 'SQL Wizard',
    shortDescription: 'Write complex SQL queries using plain English.',
    fullDescription: 'Describe the data you need ("Show me users who signed up last week from France") and get the optimized SQL query.',
    category: 'Code',
    pricing: 'Free',
    rating: 4.8,
    reviewCount: 1200,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=31',
    tags: ['Database', 'SQL', 'Developer'],
    launchDate: '2023-01-25',
  },
  {
    id: '32',
    name: 'TravelPlan AI',
    shortDescription: 'Personalized travel itineraries in seconds.',
    fullDescription: 'Input your destination, budget, and interests. Get a day-by-day plan including hidden gems and optimal routes.',
    category: 'Productivity',
    pricing: 'Freemium',
    rating: 4.6,
    reviewCount: 880,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=32',
    tags: ['Travel', 'Planning', 'Lifestyle'],
    launchDate: '2023-05-10',
  },
  {
    id: '33',
    name: 'PodcastEdit',
    shortDescription: 'Remove silence and "umms" from audio automatically.',
    fullDescription: 'Clean up your podcast recording. Detects and removes filler words, long pauses, and background noise with one click.',
    category: 'Audio',
    pricing: 'Paid',
    rating: 4.7,
    reviewCount: 340,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=33',
    tags: ['Podcast', 'Editing', 'Cleanup'],
    launchDate: '2023-09-01',
  },
  {
    id: '34',
    name: 'RecipeMind',
    shortDescription: 'Generate recipes based on ingredients in your fridge.',
    fullDescription: 'Reduce food waste. List your available ingredients and get creative, delicious recipe ideas instantly.',
    category: 'Productivity',
    pricing: 'Free',
    rating: 4.5,
    reviewCount: 1500,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=34',
    tags: ['Food', 'Cooking', 'Lifestyle'],
    launchDate: '2022-11-05',
  },
  {
    id: '35',
    name: 'Sketch2Code',
    shortDescription: 'Turn whiteboard sketches into working HTML/CSS.',
    fullDescription: 'Snap a picture of your UI sketch and get the basic frontend code to start your project.',
    category: 'Code',
    pricing: 'Paid',
    rating: 4.1,
    reviewCount: 290,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=35',
    tags: ['Frontend', 'Prototyping', 'Web Dev'],
    launchDate: '2023-03-30',
  },
  {
    id: '36',
    name: 'BookSummarizer',
    shortDescription: 'Get key insights from non-fiction books in 5 mins.',
    fullDescription: 'Digest the main concepts of best-selling business and self-help books without reading hundreds of pages.',
    category: 'Text',
    pricing: 'Freemium',
    rating: 4.4,
    reviewCount: 950,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=36',
    tags: ['Education', 'Reading', 'Summary'],
    launchDate: '2022-07-20',
  },
  {
    id: '37',
    name: 'FashionAI',
    shortDescription: 'Virtual try-on for online clothing stores.',
    fullDescription: 'See how clothes look on your specific body type before buying. Reduces returns and increases confidence.',
    category: 'Image',
    pricing: 'Enterprise',
    rating: 4.6,
    reviewCount: 120,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=37',
    tags: ['E-commerce', 'Fashion', 'Retail'],
    launchDate: '2023-12-10',
  },
  {
    id: '38',
    name: 'GiftGenius',
    shortDescription: 'Find the perfect gift for anyone.',
    fullDescription: 'Describe the person\'s age, interests, and your budget. GiftGenius suggests unique items from around the web.',
    category: 'Productivity',
    pricing: 'Free',
    rating: 4.8,
    reviewCount: 600,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=38',
    tags: ['Shopping', 'Lifestyle', 'Gifting'],
    launchDate: '2023-11-05',
  },
  {
    id: '39',
    name: 'MovieMatch',
    shortDescription: 'Hyper-personalized movie recommendations.',
    fullDescription: 'Stop scrolling Netflix. Tell MovieMatch what you liked about your favorite films, and it finds hidden gems you\'ll love.',
    category: 'Productivity',
    pricing: 'Free',
    rating: 4.5,
    reviewCount: 2000,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=39',
    tags: ['Entertainment', 'Movies', 'Discovery'],
    launchDate: '2022-10-15',
  },
  {
    id: '40',
    name: 'PresentationPal',
    shortDescription: 'Real-time speech coaching while you present.',
    fullDescription: 'Listens to your practice runs and gives feedback on pacing, filler words, and tone to make you a better public speaker.',
    category: 'Audio',
    pricing: 'Freemium',
    rating: 4.7,
    reviewCount: 300,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=40',
    tags: ['Speaking', 'Coaching', 'Career'],
    launchDate: '2023-08-10',
  },
  {
    id: '41',
    name: 'TextureGen',
    shortDescription: 'Seamless texture generation for 3D artists.',
    fullDescription: 'Create tileable textures like wood, metal, or fabric from text prompts. Includes normal, roughness, and displacement maps.',
    category: '3D',
    pricing: 'Paid',
    rating: 4.6,
    reviewCount: 180,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=41',
    tags: ['Game Dev', 'Textures', 'Art'],
    launchDate: '2023-05-01',
  },
  {
    id: '42',
    name: 'LearnLang',
    shortDescription: 'AI language tutor for conversational practice.',
    fullDescription: 'Practice speaking a new language with an AI partner that corrects your grammar and pronunciation in a supportive environment.',
    category: 'Text',
    pricing: 'Freemium',
    rating: 4.8,
    reviewCount: 1100,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=42',
    tags: ['Education', 'Language', 'Learning'],
    launchDate: '2023-01-05',
  },
  {
    id: '43',
    name: 'RegexHero',
    shortDescription: 'Explain and generate Regular Expressions.',
    fullDescription: 'Nobody likes writing Regex. Let RegexHero generate the pattern you need from a description, or explain what a pattern does.',
    category: 'Code',
    pricing: 'Free',
    rating: 4.9,
    reviewCount: 800,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=43',
    tags: ['Developer', 'Regex', 'Utility'],
    launchDate: '2022-09-20',
  },
  {
    id: '44',
    name: 'LegalDraft',
    shortDescription: 'Draft basic legal contracts and agreements.',
    fullDescription: 'Create NDAs, freelance contracts, and lease agreements tailored to your local laws in minutes.',
    category: 'Text',
    pricing: 'Paid',
    rating: 4.3,
    reviewCount: 250,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=44',
    tags: ['Legal', 'Contracts', 'Business'],
    launchDate: '2023-07-15',
  },
  {
    id: '45',
    name: 'PixelPerfect',
    shortDescription: 'Upscale low-res images without quality loss.',
    fullDescription: 'Turn pixelated icons or small photos into crisp, high-definition assets using deep learning upscaling.',
    category: 'Image',
    pricing: 'Freemium',
    rating: 4.7,
    reviewCount: 600,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=45',
    tags: ['Design', 'Upscaling', 'Photography'],
    launchDate: '2023-02-28',
  },
  {
    id: '46',
    name: 'VideoSearch',
    shortDescription: 'Search inside videos for spoken words or objects.',
    fullDescription: 'Index your video library. Search for "red car" or "budget discussion" and jump to the exact timestamp.',
    category: 'Video',
    pricing: 'Enterprise',
    rating: 4.5,
    reviewCount: 90,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=46',
    tags: ['Search', 'Video', 'Enterprise'],
    launchDate: '2023-10-20',
  },
  {
    id: '47',
    name: 'ExcelMaster',
    shortDescription: 'Generate complex Excel formulas instantly.',
    fullDescription: 'Stop struggling with nested IFs and VLOOKUPs. Tell ExcelMaster what you want to calculate, and paste the formula.',
    category: 'Productivity',
    pricing: 'Free',
    rating: 4.8,
    reviewCount: 3500,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=47',
    tags: ['Excel', 'Spreadsheets', 'Office'],
    launchDate: '2022-06-15',
  },
  {
    id: '48',
    name: 'MemeGen AI',
    shortDescription: 'Create viral memes based on current trends.',
    fullDescription: 'The AI monitors internet culture and suggests captions for popular templates that are relevant to today\'s news.',
    category: 'Image',
    pricing: 'Free',
    rating: 4.4,
    reviewCount: 1500,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=48',
    tags: ['Social Media', 'Humor', 'Viral'],
    launchDate: '2023-04-01',
  },
  {
    id: '49',
    name: 'StoryStarter',
    shortDescription: 'Overcome writer\'s block for fiction authors.',
    fullDescription: 'Generate plot twists, character names, or opening paragraphs to get your creative juices flowing again.',
    category: 'Text',
    pricing: 'Freemium',
    rating: 4.6,
    reviewCount: 400,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=49',
    tags: ['Writing', 'Fiction', 'Creative'],
    launchDate: '2023-09-10',
  },
  {
    id: '50',
    name: 'DeepFake Detect',
    shortDescription: 'Verify the authenticity of videos and audio.',
    fullDescription: 'Analyze media files for signs of AI manipulation. Essential for journalists and security professionals.',
    category: 'Video',
    pricing: 'Paid',
    rating: 4.9,
    reviewCount: 200,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=50',
    tags: ['Security', 'Verification', 'News'],
    launchDate: '2024-01-15',
  },
  {
    id: '51',
    name: 'HomeRobot',
    shortDescription: 'AI for programming custom home automation.',
    fullDescription: 'Connects all your smart devices. "Turn off lights when I start a movie" becomes a reality without complex coding.',
    category: 'Productivity',
    pricing: 'Paid',
    rating: 4.3,
    reviewCount: 300,
    websiteUrl: 'https://example.com',
    imageUrl: 'https://picsum.photos/400/300?random=51',
    tags: ['IoT', 'Smart Home', 'Automation'],
    launchDate: '2023-06-05',
  }
];

export const CATEGORIES = ['All', 'Text', 'Image', 'Video', 'Code', 'Audio', 'Productivity', '3D'];
export const PRICING_OPTIONS = ['All', 'Free', 'Freemium', 'Paid', 'Enterprise'];
